name: APIs.io APIs
description: Browse individual APIs across the APIs.io network.
image: https://apis.io/assets/branding/apisio-social-card.png
url: https://apis.apis.io

node: website
nav_active: apis

keywords:
  - APIs
  - Search
  - Discovery

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts"]
include: [".well-known"]

github_org: api-search
github_repo: apis

collections:
  apis:
    output: true
    permalink: /apis/:path/

defaults:
  - scope:
      path: ""
      type: apis
    values:
      layout: api
